### ISSUE TITLE
ChatGLM3的web demo无法运行成功

### ISSUE THREAD

**Issue by S0uLHun43r** [sophgo/LLM-TPU#18]
![image](https://github.com/sophgo/LLM-TPU/assets/17557425/b3ae8124-22f2-43ce-b73f-56b226059256)
即使安装chat包，实际chat包里并没有以下方法
![image](https://github.com/sophgo/LLM-TPU/assets/17557425/f9dbe247-0970-4882-82dc-faf33cac3eb9)

**Comment by ZIFENG278** [comment]
chat is not a python module, it is a cpp .so library which you need to compile it first

**Comment by chuxiaoyi2023** [comment]
需要编译哈，不能用pip install chat

mkdir build
cd build && cmake .. && make -j && cd ..
