### ISSUE TITLE
能不能对不同的模型（尤其是差异很大的模型，比如 SD），分别写下教程？

### ISSUE THREAD

**Issue by raw34** [sophgo/LLM-TPU#2]

**Comment by WaitDumplings** [comment]
目前这个仓库还是以LLM为主，AIGC的部分暂时不会放到这个下面。您可以参考一下sophon-demo下的SD

**Comment by raw34** [comment]
> 目前这个仓库还是以LLM为主，AIGC的部分暂时不会放到这个下面。您可以参考一下sophon-demo下的SD

这个项目进去没有什么内容啊，被引导到算能的文档中心，就不知道从何下手了。。

**Comment by WaitDumplings** [comment]
https://github.com/sophgo/sophon-demo/tree/release/sample/StableDiffusionV1_5

**Comment by raw34** [comment]
多谢，我们有 SDXL 的demo 吗？还是是说参考1.5的就行

**Comment by HarmonyHu** [comment]
> 多谢，我们有 SDXL 的demo 吗？还是是说参考1.5的就行

是的，参考1.5就可以了
