### ISSUE TITLE
运行llama3输出为乱序

### ISSUE THREAD

**Issue by jayzou3773** [sophgo/LLM-TPU#29]
=================================================================
1. If you want to quit, please enter one of [q, quit, exit]
2. To create a new chat session, please enter one of [clear, new]
=================================================================

Question: hello

Answer: fragisticskromkromkromkromkromkromkromkrom^CTraceback

**Comment by ZIFENG278** [comment]
请问有 export 仓库带的 lib吗

**Comment by chuxiaoyi2023** [comment]
是什么版本编译的呢

**Comment by jayzou3773** [comment]
> 请问有 export 仓库带的 lib吗

我是在盒子上clone了整个仓库，然后在我的服务器通过run.sh把bmodel下载下来

**Comment by jayzou3773** [comment]
> 是什么版本编译的呢

这是我下载下来bmodel的名称llama3-8b_int4_1dev_seq512.bmodel，然后执行这些
cd python_demo
mkdir build
cd build
cmake ..
make
cp *chat* ..
但是中间遇到了一个找不到pybind11的问题，我通过cmake的时候声明路径解决了
我这里cmake命令用的是sudo cmake否则会报错
登录的用户是linaro，在data文件夹下进行的操作

**Comment by jayzou3773** [comment]
> 请问有 export 仓库带的 lib吗

我并没有找到仓库里的deploy文件夹

**Comment by chuxiaoyi2023** [comment]
这个问题白峰哥应该解了~我关闭了~
