### ISSUE TITLE
请问有支持iFlytekSpark的模型计划吗

### ISSUE THREAD

**Issue by tzhang2014** [sophgo/LLM-TPU#38]
如题， 请问有支持对讯飞星火模型在算丰平台的适配吗？下面是开原地址
https://gitee.com/iflytekopensource/iFlytekSpark-13B

**Comment by chuxiaoyi2023** [comment]
sorry暂时还没有，目前人力有点不足~
如果有多余人手，我们会安排的~！

**Comment by tzhang2014** [comment]
oo,好的，感谢
