### ISSUE TITLE
关于CV180x的适配问题

### ISSUE THREAD

**Issue by xpww** [sophgo/LLM-TPU#4]
您好，我想问一下CV180x可以将这里的LLM部署于TPU吗？我想部署一个，但担心硬件方面的限制。BM似乎比CV高级得多

**Comment by WaitDumplings** [comment]
您好，现在LLM目前只适配BM1684X，CV180x系列目前没有适配计划

**Comment by xpww** [comment]
你好！那我手动适配的话，在硬件上有无可行性呢，我想尝试一下。在 2024年3月17日，03:45，Maojie Tang ***@***.***> 写道：﻿
您好，现在LLM目前只适配BM1684X，CV180x系列目前没有适配计划
