### ISSUE TITLE
How to support qwen2.5-7b-instruction ?

### ISSUE THREAD

**Issue by wuhuzi** [sophgo/LLM-TPU#49]
I have fine-tuned the qwen2.5-7b-instruction model using Llama Factory, and now I need to deploy the fine-tuned qwen2.5 model on TPU. 

How should I proceed with the support? 

I have noticed that currently, only qwen2 is supported, and there is no support for qwen2.5 yet. 
Is there a significant difference between the two? When will the qwen2.5 series models be supported?

Hope to receive a reply.

Thanks.

**Comment by baifengbai** [comment]
take this url , https://github.com/sophgo/LLM-TPU/tree/main/models/Qwen2_5/compile
