### ISSUE TITLE
se7盒子1684X跑MiniCPM-V-2_6不稳且推理精度差

### ISSUE THREAD

**Issue by nw-wf** [sophgo/LLM-TPU#59]
1. 自己没转，估计照着教程也有很多坑，所以直接下载转好的模型minicpmv26_bm1684x_int4_seq1024.bmodel
2. 运气不错，直接跑起来了，但是，根据多年做阅读理解的经验，出现but转折，肯定就是重点
3. 出现了三种情况，贴一个大图吧
![image](https://github.com/user-attachments/assets/009c7eed-0cc3-4008-b48a-4a788ea2c8dd)
  3.1 推理一堆乱码，如上图红框所示
  3.2 接着问同一张图，嘿，推理成功了，但是就是不知所云，如上图绿框所示
  3.3 换一张图就崩了，报RuntimeError，如上图黄框所示
4. 图片是随便网上下的，可以贴，所以你们复现吧。（当测试的感觉真爽，难怪坐我对面的测试整天乐呵呵的，haha）
@chuxiaoyi2023 

fight_2.jpg
![fight_2](https://github.com/user-attachments/assets/b2850d78-a02f-46a5-b08b-bc47e90b8769)

fight_3.jpg
![fight_3](https://github.com/user-attachments/assets/c3434286-0082-4b90-bfda-a3a5fbc113ac)

**Comment by xuyang1102** [comment]
minicpmv26_bm1684x_int4.bmodel
现在推理代码改成了图片切片多图推理，还有bug的，你可以用原来的代码，单图不切片推理，用上面那个bmodel，精度还行

**Comment by chuxiaoyi2023** [comment]
![image](https://github.com/user-attachments/assets/a6085337-b37b-4b45-98f6-4dd4e0125cf6)

pipeline.py里面的代码改成
```python
    def encode(self):
        if not self.image_str:
            inserted_image_str = ""
        else:
            inserted_image_str = "(<image>./</image>)\n"
            image = Image.open(self.image_str).convert('RGB')

        sample_image = Image.open("test0.jpg").convert('RGB')
        image = image.resize(sample_image.size, Image.LANCZOS)
        msgs = [{'role': 'user', 'content': '{}{}'.format(inserted_image_str, self.input_str)}]
        prompts_lists = self.processor.tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)

        inputs = self.processor(
            prompts_lists,
            [[image]] if image else None,
            max_slice_nums=self.MAX_SLICE_NUMS,
            use_image_id=None,
            return_tensors="pt",
            max_length=8192
        )
        self.input_ids = inputs.input_ids[0]
        self.pixel_values = torch.cat(inputs["pixel_values"][0], dim=0).flatten().tolist()
        self.image_offsets = torch.where(self.input_ids==128244)[0].tolist()
        self.patch_num = len(inputs["pixel_values"][0])

        self.input_ids = self.input_ids.tolist()
```


问题原因是我们模型是固定输入的，图片输入和你转的bmodel输入不同，就会有问题
所以需要有一个resize操作
但是resize操作会损失精度

如果想要不损失精度，就要转你们图像大小的模型

之后我们会考虑怎么比较优雅的处理动态图像输入，不过目前还是静态的

**Comment by nw-wf** [comment]
> ![image](https://private-user-images.githubusercontent.com/125880866/392296728-a6085337-b37b-4b45-98f6-4dd4e0125cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMDc2ODcsIm5iZiI6MTczMzMwNzM4NywicGF0aCI6Ii8xMjU4ODA4NjYvMzkyMjk2NzI4LWE2MDg1MzM3LWIzN2ItNGI0NS05OGY2LTRkZDRlMDEyNWNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxMDE2MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzVjOWI2YmEzYmNhYTdiM2RlM2JjMDQzNGFmYTg4MTMzMGY1Njg5MDVlZTg3YjQyNjVmNTkxMzMyNjE0NjJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.JCTBxUfmGJ_pgAtgzMOBW_d6RjijNbX70Jr0GXuXymg)
> 
> pipeline.py里面的代码改成
> 
> ```python
>     def encode(self):
>         if not self.image_str:
>             inserted_image_str = ""
>         else:
>             inserted_image_str = "(<image>./</image>)\n"
>             image = Image.open(self.image_str).convert('RGB')
> 
>         sample_image = Image.open("test0.jpg").convert('RGB')
>         image = image.resize(sample_image.size, Image.LANCZOS)
>         msgs = [{'role': 'user', 'content': '{}{}'.format(inserted_image_str, self.input_str)}]
>         prompts_lists = self.processor.tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
> 
>         inputs = self.processor(
>             prompts_lists,
>             [[image]] if image else None,
>             max_slice_nums=self.MAX_SLICE_NUMS,
>             use_image_id=None,
>             return_tensors="pt",
>             max_length=8192
>         )
>         self.input_ids = inputs.input_ids[0]
>         self.pixel_values = torch.cat(inputs["pixel_values"][0], dim=0).flatten().tolist()
>         self.image_offsets = torch.where(self.input_ids==128244)[0].tolist()
>         self.patch_num = len(inputs["pixel_values"][0])
> 
>         self.input_ids = self.input_ids.tolist()
> ```
> 
> 问题原因是我们模型是固定输入的，图片输入和你转的bmodel输入不同，就会有问题 所以需要有一个resize操作 但是resize操作会损失精度
> 
> 如果想要不损失精度，就要转你们图像大小的模型
> 
> 之后我们会考虑怎么比较优雅的处理动态图像输入，不过目前还是静态的

效率点赞，完事我试试，多谢多谢！

**Comment by nw-wf** [comment]
> minicpmv26_bm1684x_int4.bmodel 现在推理代码改成了图片切片多图推理，还有bug的，你可以用原来的代码，单图不切片推理，用上面那个bmodel，精度还行

感谢回复，有空我再试试！

**Comment by nw-wf** [comment]
> ![image](https://private-user-images.githubusercontent.com/125880866/392296728-a6085337-b37b-4b45-98f6-4dd4e0125cf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNjU1NTEsIm5iZiI6MTczMzM2NTI1MSwicGF0aCI6Ii8xMjU4ODA4NjYvMzkyMjk2NzI4LWE2MDg1MzM3LWIzN2ItNGI0NS05OGY2LTRkZDRlMDEyNWNmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNVQwMjIwNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmJhNDAxMjk4YTAzMzNkM2U5YzA0OTIxM2NmNDYzMGY2ODFkMGRiMDU5NmVkZDdjNjZjODQzYWU3MmVhYzFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1lfI4mcCuaGPTxujZ_1ypoSFs78O0FqVdOnChBjhUJo)
> 
> pipeline.py里面的代码改成
> 
> ```python
>     def encode(self):
>         if not self.image_str:
>             inserted_image_str = ""
>         else:
>             inserted_image_str = "(<image>./</image>)\n"
>             image = Image.open(self.image_str).convert('RGB')
> 
>         sample_image = Image.open("test0.jpg").convert('RGB')
>         image = image.resize(sample_image.size, Image.LANCZOS)
>         msgs = [{'role': 'user', 'content': '{}{}'.format(inserted_image_str, self.input_str)}]
>         prompts_lists = self.processor.tokenizer.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True)
> 
>         inputs = self.processor(
>             prompts_lists,
>             [[image]] if image else None,
>             max_slice_nums=self.MAX_SLICE_NUMS,
>             use_image_id=None,
>             return_tensors="pt",
>             max_length=8192
>         )
>         self.input_ids = inputs.input_ids[0]
>         self.pixel_values = torch.cat(inputs["pixel_values"][0], dim=0).flatten().tolist()
>         self.image_offsets = torch.where(self.input_ids==128244)[0].tolist()
>         self.patch_num = len(inputs["pixel_values"][0])
> 
>         self.input_ids = self.input_ids.tolist()
> ```
> 
> 问题原因是我们模型是固定输入的，图片输入和你转的bmodel输入不同，就会有问题 所以需要有一个resize操作 但是resize操作会损失精度
> 
> 如果想要不损失精度，就要转你们图像大小的模型
> 
> 之后我们会考虑怎么比较优雅的处理动态图像输入，不过目前还是静态的

这次可以了，没有乱码，也不蹦了
![image](https://github.com/user-attachments/assets/7d1dd578-d788-4cd9-9630-7834830a97e3)

**Comment by xuyang1102** [comment]
@chuxiaoyi2023 转换后的模型固定输入后输出都是固定的对吧？没有top_k、temperature这些随机因素了吗？

**Comment by chuxiaoyi2023** [comment]
这个模型没有，这个模型用的直接是贪婪的做法，参考export_onnx
```python
class LmHead(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.lm_head = origin_model.llm.get_output_embeddings()

    def forward(self, hidden_states):
        hidden_states = transformer.norm(hidden_states)
        m_logits = self.lm_head(hidden_states)
        _, token = torch.topk(m_logits.float(), 1)
        return tokenclass LmHead(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.lm_head = origin_model.llm.get_output_embeddings()

    def forward(self, hidden_states):
        hidden_states = transformer.norm(hidden_states)
        m_logits = self.lm_head(hidden_states)
        _, token = torch.topk(m_logits.float(), 1)
        return token
```

Qwen2这些是有的
```python
# refs:https://github.com/huggingface/transformers/blob/main/src/transformers/generation/logits_process.py
class PenaltySampleHead(torch.nn.Module):

    def __init__(self, top_k = 50, min_tokens_to_keep = 5):
        super().__init__()
        self.top_k = top_k
        self.min_tokens_to_keep = min_tokens_to_keep
        self.keep_matrix = torch.zeros((1, self.top_k), dtype=torch.bool)
        self.keep_matrix[0, :self.min_tokens_to_keep] = True

    def forward(self, m_logits, input_ids, top_p, temperature, penalty):
        # repeat penalty
        logits = torch.gather(m_logits, 1, input_ids)
        logits = torch.where(logits < 0, logits * penalty, logits / penalty)
        m_logits.scatter_(1, input_ids, logits)

        # top_k
        logits, token = torch.topk(m_logits.float(), self.top_k)

        # temperature
        logits = logits / temperature

        # top_p
        cumulative_probs = logits.softmax(dim=1).cumsum(dim=1)
        mask = cumulative_probs < top_p
        mask = mask + self.keep_matrix
        filtered_logits = torch.where(mask, logits, torch.FloatTensor([-1000.]))
        probs = filtered_logits.softmax(dim=1)
        return probs, token
```

然后加了后还要改chat.cpp，和pipeline.py，你可以自己先加加，我们来安排的话可能比较慢ovo

**Comment by chuxiaoyi2023** [comment]
对的输入输出都是固定的了
